### ISSUE TITLE
Default setting option for sound volume control

### ISSUE THREAD

**Issue by denkiwakame** [toio/toio-spec#43]
Hi, thank you for maintaining the awesome toio platform.
Let me ask several questions about default sound control as follows.

### How to control validation sound when BLE connection is established
- It would be really happy if I could control the ``default'' sound volume of toio (0x00-0xff) when power-on/off and BLE is established.
- It seems, the validation sound for ``BLE connection established'' is pre-programmed and we cannot control it via BLE characteristics APIs.
- Do you have any plan to update the toio firmware and BLE APIs so that we can control the default sound volumes?
  - Currently, configuration via BLE APIs are not persistent. Would it be impossible to change the default sound volume unless we directly modify the toio firmware? https://github.com/toio/toio-spec/blob/main/docs/configuration.md#%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF%E6%93%8D%E4%BD%9C

**Comment by TakeshiYaeda** [comment]
@denkiwakame Sorry for my late reply.

Thanks you for using toio and toio-spec!
Regarding sound control, we don't have any plan to make the volume controllable for the following reason.

1. If the volume is turned down or completely muted, it will be difficult to recognize the state of the cube, and we would like to avoid such a situation from a UX perspective.
2. Changing the volume will not have the desired effect due to speaker performance/quority.

**Comment by denkiwakame** [comment]
@TakeshiYaeda I am sorry that I did not notice your kind reply immediately. I deeply appreciate your help, and I am now convinced that we cannot control the sound volume in the user layer. Thank you again for adequately disclosing the design concept. I will close this issue.
